#This notebook contains the basics of Python where we learned about lists, tuples, strings, and dictionaries. This notebook contains what we learned in week 1. 

1. Scenario: You have a list of integers, and you need to find the maximum
value in the list.
a. Question: How would you find the maximum value from the
following list?

In [1]:
# create a list with numbers 
num = [1,2,3,4,5,6,7]
max(num) # max is used for maximum 

7

2. Scenario: You need to concatenate a list of strings into a single string,
with each string separated by a comma.
a. Question: How would you combine the following list of strings into
a single string?

In [61]:
my_list = ['I', 'love', 'Dogs']
separator = ' '  # seperator helps for the gap
result = separator.join(my_list) # To concatenate separator and join is used 
print(result)


I love Dogs


3. Scenario: You have a dictionary where the keys are names and the
values are ages. You need to retrieve the age of a specific person.
a. Question: How would you get the age of "Dev" from the following
dictionary?

In [1]:
#create a list with name and age 
mydict = { "Name": "Dev", "Age": "30"}
x = mydict["Age"] 
print(x)

30


4. Scenario: You need to remove duplicate elements from a list while
preserving the original order of elements.
a. Question: How would you remove duplicates from the following
list?

In [22]:
#Create a list with duplicate number 
num = [1,2,3,4,5,2,3]
num[:5] # By slicing duplicate numbers are removed 

[1, 2, 3, 4, 5]

5. Scenario: You have a NumPy array and need to compute the sum of all
its elements.
a. Question: How would you find the sum of elements in the
following NumPy array?

In [65]:
import numpy as np
np.sum([1,2,3,4,5,6,7,8,9])

45

6. Scenario: You have a 2D NumPy array and need to get the maximum
value from each column.
a. Question: How would you find the maximum values for each
column in the following array?

In [40]:
# 2-D numpy array
nd2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
nd2 = np.amax(nd2, axis=1)
nd2

array([ 5, 10])

7. Scenario: You have a DataFrame and need to sort it by a specific column.
a. Question: How would you sort the DataFrame by the "Age"
column?

In [ ]:
df["Age"]

8. Scenario: You need to calculate the total sum of a column in a
DataFrame.
a. Question: How would you find the sum of the "Sales" column?

In [ ]:
# To sum we have to sum()
Total_Sales = df["Sales"].sum() 
print (df)

9. Scenario: You need to check if a variable is of type int.
a. Question: How would you verify if a variable x is an integer?

In [69]:
variable = "x, y, z"
if "x" in variable:
    print("x is an integar")
else:
    print("x is not integar")

x is an integar


10.Scenario: You have a list of mixed types and need to create separate lists
for integers, floats, and strings.
a. Question: How would you categorize the following mixed list into
different types?

In [82]:
mylist = ([1,2, 0.1, 0.2, 'apple', 'berries', 'cherry'])
integers =[]
floats =[]
strings = []
 # Seperate through the mixed list 
for item in mylist:
    if isinstance (item, int):  # isinstance if the item is integers
        integers.append(item)
    elif isinstance(item, float):  # isintegar if item is float 
        floats.append(item)
    elif isinstance(item, str):  # isinstance if item is strings 
        strings.append(item)
# Output the categorized lists
print("Integers:", integers)  
print("Floats:", floats)      
print("Strings:", strings)


Integers: [1, 2]
Floats: [0.1, 0.2]
Strings: ['apple', 'berries', 'cherry']


11.Scenario: You are given a string of comma-separated numbers. You
need to convert this string into a list of integers.
a. Question: How would you achieve this conversion?

In [84]:
# Using a For Loop
string_list = ['1', '2', '3', '4', '5']
integer_list = []

for s in string_list:
    integer_list.append(int(s))

print(integer_list)


[1, 2, 3, 4, 5]


12.Scenario: You need to reverse the words in a sentence while keeping the
order of the words intact.
a. Question: How would you reverse each word in the following
sentence?

In [94]:
def reverse_words(string):
  
    # Split words in the given string
    # and reverse the order
    reversed_words = string.split()[::-1]
    
    # Join the reversed words into a 
    # single string
    return " ".join(reversed_words)

# Input string
string = " I love pizza "
print(reverse_words(string))

pizza love I


13. Scenario: You need to combine two lists into a dictionary where the
elements of the first list are keys and the elements of the second list are
values.
a. Question: How would you combine the following lists into a
dictionary?

In [44]:
#To combine the list we use zip 
dict(zip(['Dev','Ajay', 'Rohit'], [22, 24, 34]))

{'Dev': 22, 'Ajay': 24, 'Rohit': 34}

14.Scenario: You are given a list of tuples where each tuple contains a name
and an age. You need to sort this list by age.
a. Question: How would you sort the following list of tuples by age?

In [96]:
people =  [('Dev',34), ('Rohit', 21), ('Ajay', 32)]
#Sort the list of tuples by age (the second element in each tuple)
sorted_people = sorted(people, key=lambda x: x[1])

print(sorted_people)


[('Rohit', 21), ('Ajay', 32), ('Dev', 34)]


15.Scenario: You have a 2D NumPy array and need to calculate the mean
value of each row.
a. Question: How would you compute the mean value for each row
in the following array?

In [86]:
#To calculate a mean for a row we use axis 0 
nd1 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
nd1 = np.mean(nd1, axis=0)
nd1

array([3.5, 4.5, 5.5, 6.5, 7.5])

16.Scenario: You need to create a NumPy array of size 10 filled with zeros,
and then set the fifth element to 5.
a. Question: How would you create and modify the array as
described?

In [42]:
#create a numpy array with 10 zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

17. Scenario: You have a DataFrame and need to find the median of a
numeric column.
a. Question: How would you find the median of the "Scores" column
in the following DataFrame?

In [ ]:
median_score = df['Scores'].median() # Use median() scores column 
print(median_score)

18.Scenario: You need to filter rows where the value in the "Sales" column
is above 100 and then sort these rows by "Date" in descending order.
a. Question: How would you filter and sort the DataFrame based on
the given criteria?

In [ ]:
# Filter rows where 'Sales' > 100
filtered_df = df[df['Sales'] > 100]

# Sort the filtered DataFrame by 'Date' in descending order
sorted_filtered_df = filtered_df.sort_values(by='Date', ascending=False)

print(sorted_filtered_df)

19.Scenario: You have a string containing a number and need to convert it
to an integer. Additionally, handle the case where the string might not
represent a valid integer.
a. Question: How would you safely convert the string "42" to an
integer and handle invalid cases?

20.Scenario: You have a list containing different data types, and you want
to separate out all the strings.
a. Question: How would you extract all string elements from the
following list?

In [92]:
data_types = [ 1, 2, "python", 50, "Bootcamp"] # Mixed data types
strings = [item for item in data_types if isinstance(item, str)]  

print(strings)

['python', 'Bootcamp']
